---
version: "3"
services:
  minibook:
    build: .
    image: minibook-nginx:latest
    container_name: minibook-nginx
    # environment:
    #   - TZ=America/Detroit
    # volumes:
    #   - ./custom:/usr/share/nginx/html
    restart: unless-stopped
    labels:
      - traefik.http.routers.minibook-frontend.rule=Host(`minibook.io`)
      - traefik.http.routers.minibook-frontend.tls=true
      - traefik.http.routers.minibook-frontend.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - web

networks:
  web:
    external: true